<?php

$keywords = array(
    "logo amt",
    "my showroom",
    "car leasing made easy",
    "lamborghini huracan lease",
    "lamborghini lease",
    "car leasing yorkshire",
    "amt motors",
    "bentley contract hire",
    "lamborghini lease uk",
    "maserati lease calculator",
    "lamborghini aventador lease",
    "audi rs7 lease",
    "ferrari lease",
    "leasing ferrari",
    "bentley leasing",
    "ferrari leasing",
    "can you part exchange for a leased car",
    "audi rs7 hire uk",
    "yorkshire leasing",
    "contract vehicle leasing uk",
    "rolls royce business lease",
    "bentley continental gt lease",
    "bik company car tax calculator",
    "leasing a business with option to buy",
    "audi a3 e tron lease",
    "car lease part exchange",
    "leasing uk ltd leeds",
    "audi r8 contract hire",
    "aston martin contract hire",
    "amt leasing",
    "car leasing leeds",
    "rolls royce lease",
    "aston martin vantage lease",
    "bentley bentayga lease deals",
    "seat leon cupra 300 lease deals",
    "aston martin lease",
    "ferrari contract hire",
    "business car lease tax calculator",
    "mercedes viano lease",
    "ferrari lease rates",
    "contract vehicle leasing",
    "aston martin leasing",
    "t and t leasing",
    "lotus evora lease special",
    "porsche cayenne contract hire",
    "mclaren lease",
    "van leasing leeds",
    "company car bik calculator",
    "bentley lease deals",
    "ferrari california lease",
    "porsche panamera turbo lease",
    "amt car leasing",
    "lease bentley price",
    "audi r8 lease hire",
    "van leasing",
    "van lease deals",
    "contract hire leasing",
    "poor credit car leasing",
    "tesla lease uk",
    "car leasing scotland",
    "land rover discovery lease",
    "bad credit van leasing",
    "van trackers",
    "contract car leasing",
    "business van lease",
    "audi rs3 lease",
    "van contract hire",
    "12 month car lease",
    "audi r8 hire",
    "van lease hire",
    "vw amarok lease",
    "man tge",
    "company car allowance",
    "lease calculator",
    "contract hire vans",
    "lease hire vans",
    "audi contract hire",
    "seat ateca lease deals",
    "van leasing no credit check",
    "compare lease cars",
    "audi a3 saloon lease",
    "bad credit car leasing uk",
    "fiat fullback lease",
    "arval contact",
    "volvo car leasing",
    "porsche lease deals",
    "ford ranger wildtrak lease",
    "ford ranger lease deals",
    "commercial vehicle leasing",
    "audi lease deals uk",
    "personal van leasing",
    "van lease purchase",
    "contract and leasing",
    "l200 lease",
    "bmw m4 hire",
    "uk car contracts",
    "benefit in kind tax calculator",
    "audi a7 lease",
    "e class coupe lease",
    "best van lease deals",
    "velar lease deals",
    "bvrla guidelines",
    "mitsubishi l200 lease",
    "bik tax calculator",
    "premier car leasing",
    "mercedes glc coupe lease",
    "leasing a car through a limited company",
    "bvrla fair wear and tear guide",
    "audi s3 saloon lease",
    "hyundai car lease",
    "bentley finance",
    "smart car lease deals",
    "peugeot contract hire",
    "rent to buy cars uk",
    "piaggio ape 50",
    "transit van lease",
    "van leasing scotland",
    "sports car lease",
    "car lease calculator uk",
    "audi q5 lease deals",
    "tesla contract hire",
    "personal car leasing scotland",
    "car leasing nottingham",
    "vw transporter sportline lease",
    "car leasing south wales",
    "company van tax calculator",
    "car leasing comparison uk",
    "fair wear and tear guide",
    "van lease deals uk",
    "audi rs6 hire",
    "commercial van leasing",
    "bik car tax calculator",
    "audi hire",
    "auto leasing",
    "lease calculator uk",
    "tesla model s lease uk",
    "l200 lease deals",
    "capital car leasing",
    "audi rs3 hire",
    "van leasing special offers",
    "12 month personal car lease",
    "citroen van lease",
    "no initial payment car leasing",
    "car lease tax",
    "excess mileage charge calculator",
    "lambo hire",
    "car leasing websites",
    "business car leasing tax implications",
    "courtesy car leasing",
    "car benefit in kind tax calculator",
    "leasys car leasing",
    "tesla car lease",
    "electric van lease",
    "sq5 lease",
    "businesscar",
    "glc coupe lease deals",
    "porsche contract hire",
    "new business car lease",
    "audi a4 estate lease",
    "tesla lease deals",
    "peugeot traveller lease",
    "premium car lease",
    "infiniti q30 lease deals",
    "lease purchase vans",
    "amt it",
    "mercedes x class lease",
    "citroen c4 grand picasso lease",
    "van leasing with insurance included",
    "van contract hire and leasing special offers",
    "limited company car lease",
    "leasing auta w uk",
    "4x4 pickup leasing",
    "poor credit van leasing",
    "phantom car hire",
    "cayman lease special",
    "van lease offers",
    "iveco daily 70c21",
    "car leasing stockport",
    "personal car leasing bad credit",
    "vw transporter lease deals",
    "hitachi capital car leasing",
    "smart track vehicle tracking",
    "range rover evoque convertible lease",
    "contract hire and leasing vans",
    "business car leasing bmw",
    "difference between hire and lease",
    "car leasing poor credit history",
    "porsche panamera lease deals",
    "porsche 991 lease",
    "contract hire and",
    "bentley mulsanne hire",
    "cheapest tesla lease",
    "maserati lease uk",
    "global van hire",
    "discovery 4 lease",
    "bentley gtc hire",
    "smart leasing",
    "cheap lease vans",
    "porsche cayman hire",
    "porsche car lease",
    "ingenium dynamics dashboard",
    "c63 lease deals",
    "peugeot van lease",
    "lamborghini finance calculator",
    "pick up truck contract hire deals",
    "car trackers leeds",
    "aston martin rapide s hire",
    "personal car leasing poor credit",
    "audi tt convertible lease deals",
    "bentley bentayga hire uk",
    "tax implications of leasing a car",
    "business car lease criteria",
    "new van lease",
    "cla shooting brake lease",
    "amt solutions",
    "difference between finance lease and contract hire",
    "ford ranger personal lease deals",
    "iveco daily 35c16",
    "mitsubishi l200 lease deals",
    "leasing audi q7 e tron",
    "compare van lease",
    "fair condition car",
    "personal contract hire do i need gap insurance",
    "amt s",
    "citroen contract hire",
    "info lease",
    "lease purchase companies",
    "lexus lease options",
    "black horse leasing",
    "lease to own business",
    "first class auto leasing",
    "640 4",
    "arval contact email",
    "bmw 2 year lease",
    "business contract hire tax implications",
    "crew cab lease hire",
    "vrs car leasing",
    "van lease specials",
    "business vans lease",
    "subaru impreza contract hire",
    "lease residual value guide",
    "tesla model s leasing",
    "crew cab vans lease hire",
    "how to lease a vehicle for a business",
    "your new car leasing",
    "isuzu blade contract hire",
    "new vans for lease",
    "cheap car leasing bad credit",
    "maserati car hire",
    "black horse contract hire",
    "car leasing scotland bad credit",
    "abarth 695 lease",
    "ford ranger wildtrak leasing",
    "best luxury car lease deals uk",
    "ldv v80 price uk",
    "lease price calculator",
    "infiniti lease uk",
    "ford transit van lease",
    "ford ranger lease deals uk",
    "contract hire and leasing difference",
    "leasing audi a3 sportback",
    "lease m140i",
    "g63 lease",
    "jaguar xe r sport lease deals",
    "discovery sport contract hire deals",
    "lamborghini gallardo lease price",
    "lease hire co uk",
    "vehicle leasing scotland",
    "2 year van lease deals",
    "van contract hire deals",
    "mercedes benz e class lease deals",
    "business van lease deals",
    "car lease 12 month contract",
    "mini lease calculator",
    "minilease",
    "audi a3 cabriolet lease",
    "contract vans",
    "company car and fuel tax calculator",
    "car tax calculator company",
    "company car lease tax",
    "ford transit lease deals",
    "buy amt uk",
    "nissan leasing company",
    "porsche boxster hire",
    "audi a3 sportback personal lease",
    "simple car leasing",
    "lease my car",
    "new business van leasing",
    "prestige vehicle leasing",
    "tm van hire",
    "ferrari f40 hire",
    "compare van lease deals",
    "vauxhall corsa contract hire",
    "company car or cash allowance",
    "vw amarok contract hire",
    "vehicle hire and leasing",
    "global rental & leasing",
    "porsche lease calculator",
    "ferrari california hire",
    "12 month van lease",
    "vehicle leasing solutions",
    "aston martin lease deals",
    "bentley continental gt hire",
    "transit deals",
    "car benefit tax calculator",
    "guaranteed lease hire",
    "audi a1 sportback lease deals",
    "new van lease deals",
    "sprinter lease deals",
    "bmw contract hire and leasing special offers",
    "cheap bentley hire",
    "porsche carrera s lease",
    "audi a8 lease deals",
    "ferrari lease payment",
    "business van finance",
    "ford ranger lease hire",
    "leasing vw amarok",
    "audi a4 car lease",
    "audi rs5 hire",
    "perk calculator",
    "shogun catering",
    "lease a kia soul for 99",
    "ferrari ff hire",
    "vehicle lease management",
    "ferrari hire leeds",
    "aventador hire",
    "easy car leasing",
    "aston martin vanquish hire",
    "isuzu contract hire",
    "lease mileage",
    "amt uk",
    "bmw m5 hire",
    "aston martin rapide hire",
    "guaranteed van finance no deposit",
    "contract hire vans uk",
    "amt ltd",
    "vans for lease uk",
    "no credit check van contract hire",
    "vans lease deals",
    "how do i lease a car through my business",
    "lease exchange",
    "lexus hybrid lease deals",
    "van lease purchase no deposit",
    "poor credit leasing",
    "lotus lease",
    "car leasing blackburn",
    "retail complaints procedure",
    "swift car lease",
    "vw sportline lease",
    "vivaro lease deals",
    "lease hire vans uk",
    "car lease deals scotland",
    "lease any car",
    "vw transporter contract hire",
    "amt group",
    "adt special deals",
    "bad credit contract hire",
    "bad credit contract hire",
    "van leasing made simple",
    "finance lease or contract hire",
    "van lease hire deals",
    "nissan van lease",
    "commercial van finance",
    "add tax calculator",
    "vehicle contracts and leasing",
    "alpha car leasing",
    "porsche 911 carrera s lease",
    "how to lease a van",
    "hybrid suv lease specials",
    "320i lease",
    "lotus elise lease",
    "best van contract hire deals",
    "vehicle contracts ltd",
    "contract lease vans",
    "mitsubishi l200 lease hire",
    "car leasing faq",
    "mitsubishi outlander contract hire",
    "bentley gt hire",
    "renault twizy hire",
    "personal contract hire bad credit",
    "e63 amg lease",
    "contract hire vs lease",
    "leasing process",
    "personal car tax calculator",
    "subaru contract hire",
    "cheap van leasing for bad credit",
    "cayman s lease",
    "how much is it to lease a lamborghini",
    "cayenne lease",
    "compare leasing quotes",
    "fiat ducato cab chassis",
    "transit lease deals",
    "mitsubishi warrior lease",
    "piaggio ape van",
    "van lease prices",
    "ford transit van lease deals",
    "fiat doblo cargo dimensions",
    "vw amarok leasing",
    "compare contract hire and leasing",
    "salary package car calculator",
    "hyundai van lease",
    "maserati lease deals",
    "12 month auto lease",
    "porsche boxster lease deals",
    "a7 lease",
    "volvo car lease",
    "alfa romeo leasing",
    "windmill car leasing",
    "bmw 3 series touring lease deals",
    "macan lease deals",
    "lease hire range rover sport",
    "private car leasing scotland",
    "lex personal car leasing",
    "best van lease deals uk",
    "leasing for business",
    "arval contract hire",
    "3 series lease",
    "personal car leasing deals with maintenance",
    "co car tax calculator",
    "citroen c4 grand picasso lease deals",
    "citroen berlingo van lease deals",
    "toyota hilux leasing",
    "ranger lease",
    "range rover hire leeds",
    "van contract purchase",
    "hybrid car lease specials"
);
$debug = false;
$groups = [];
$exclusions = ["is", "own", "co", "and", "do", "of", "it", "with", "for", "you", "or", "any", "in", "the", "at", "a", "i", "uk", "amt", "car", "lease", "leasing", "deals", "how", "much", "to", "what", "company", "go", "hire", "does", "mean", "included", "what's", "phone", "number", "up", "leeds", "my", "which", "van", "offers", "special" ];

$data = array (
    'logo_amt' => [10,31.47],
    'my_showroom' => [40,44.27],
    'car_leasing_made_easy' => [10,46.89],
    'lamborghini_huracan_lease' => [90,47.9],
    'lamborghini_lease' => [390,48.66],
    'car_leasing_yorkshire' => [110,50.57],
    'amt_motors' => [10,51.6],
    'bentley_contract_hire' => [20,52],
    'lamborghini_lease_uk' => [110,52.68],
    'maserati_lease_calculator' => [10,52.68],
    'lamborghini_aventador_lease' => [10,53.1],
    'audi_rs7_lease' => [10,54.61],
    'ferrari_lease' => [390,55.42],
    'leasing_ferrari' => [10,55.9],
    'bentley_leasing' => [10,56.3],
    'ferrari_leasing' => [10,57.17],
    'can_you_part_exchange_for_a_leased_car' => [10,57.36],
    'audi_rs7_hire_uk' => [90,57.46],
    'yorkshire_leasing' => [70,57.59],
    'contract_vehicle_leasing_uk' => [30,57.62],
    'rolls_royce_business_lease' => [90,57.94],
    'bentley_continental_gt_lease' => [30,57.94],
    'bik_company_car_tax_calculator' => [40,58.49],
    'leasing_a_business_with_option_to_buy' => [10,58.69],
    'audi_a3_e_tron_lease' => [110,58.72],
    'car_lease_part_exchange' => [140,58.93],
    'leasing_uk_ltd_leeds' => [20,59.06],
    'audi_r8_contract_hire' => [10,59.23],
    'aston_martin_contract_hire' => [20,59.33],
    'amt_leasing' => [1000,59.38],
    'car_leasing_leeds' => [480,59.75],
    'rolls_royce_lease' => [210,59.93],
    'aston_martin_vantage_lease' => [30,59.97],
    'bentley_bentayga_lease_deals' => [70,60.04],
    'seat_leon_cupra_300_lease_deals' => [70,60.07],
    'aston_martin_lease' => [320,60.21],
    'ferrari_contract_hire' => [20,60.29],
    'business_car_lease_tax_calculator' => [70,60.75],
    'mercedes_viano_lease' => [10,60.78],
    'ferrari_lease_rates' => [10,61.04],
    'contract_vehicle_leasing' => [390,61.52],
    'aston_martin_leasing' => [10,61.63],
    't_and_t_leasing' => [70,61.67],
    'lotus_evora_lease_special' => [90,61.85],
    'porsche_cayenne_contract_hire' => [70,61.92],
    'mclaren_lease' => [70,61.93],
    'van_leasing_leeds' => [20,61.98],
    'company_car_bik_calculator' => [210,62.08],
    'bentley_lease_deals' => [10,62.1],
    'ferrari_california_lease' => [90,62.12],
    'porsche_panamera_turbo_lease' => [70,62.36],
    'amt_car_leasing' => [140,62.45],
    'lease_bentley_price' => [90,62.57],
    'audi_r8_lease_hire' => [10,62.7],
    'van_leasing' => [18100,57.16],
    'van_lease_deals' => [2400,59.17],
    'contract_hire_leasing' => [2400,62.28],
    'poor_credit_car_leasing' => [1900,52.49],
    'tesla_lease_uk' => [1600,60.12],
    'car_leasing_scotland' => [1300,61.54],
    'land_rover_discovery_lease' => [1300,62.15],
    'bad_credit_van_leasing' => [1000,55.43],
    'van_trackers' => [1000,58.94],
    'contract_car_leasing' => [1000,60.97],
    'business_van_lease' => [880,56.05],
    'audi_rs3_lease' => [1000,61.85],
    'van_contract_hire' => [1000,61.93],
    '12_month_car_lease' => [1000,62.23],
    'audi_r8_hire' => [720,50.81],
    'van_lease_hire' => [880,60.84],
    'vw_amarok_lease' => [880,61.71],
    'man_tge' => [720,55.5],
    'company_car_allowance' => [720,58.4],
    'lease_calculator' => [720,59.52],
    'contract_hire_vans' => [590,56.69],
    'lease_hire_vans' => [590,59.63],
    'audi_contract_hire' => [590,62.8],
    'seat_ateca_lease_deals' => [590,62.94],
    'van_leasing_no_credit_check' => [390,46.91],
    'compare_lease_cars' => [480,59.25],
    'audi_a3_saloon_lease' => [480,60.06],
    'bad_credit_car_leasing_uk' => [480,60.07],
    'fiat_fullback_lease' => [480,60.39],
    'arval_contact' => [480,60.74],
    'volvo_car_leasing' => [480,61.33],
    'porsche_lease_deals' => [480,62.01],
    'ford_ranger_wildtrak_lease' => [480,62.13],
    'ford_ranger_lease_deals' => [480,62.15],
    'commercial_vehicle_leasing' => [480,62.74],
    'audi_lease_deals_uk' => [480,62.95],
    'personal_van_leasing' => [390,56.39],
    'van_lease_purchase' => [390,58.13],
    'contract_and_leasing' => [390,58.39],
    'l200_lease' => [390,60.34],
    'bmw_m4_hire' => [320,52.48],
    'uk_car_contracts' => [390,61.46],
    'benefit_in_kind_tax_calculator' => [390,61.57],
    'audi_a7_lease' => [390,61.65],
    'e_class_coupe_lease' => [390,62.82],
    'best_van_lease_deals' => [320,57.91],
    'velar_lease_deals' => [320,58.94],
    'bvrla_guidelines' => [320,59.57],
    'mitsubishi_l200_lease' => [320,60.26],
    'bik_tax_calculator' => [320,60.59],
    'premier_car_leasing' => [320,60.7],
    'mercedes_glc_coupe_lease' => [320,60.87],
    'leasing_a_car_through_a_limited_company' => [260,53.19],
    'bvrla_fair_wear_and_tear_guide' => [320,62.2],
    'audi_s3_saloon_lease' => [320,62.42],
    'hyundai_car_lease' => [320,62.5],
    'bentley_finance' => [260,56.53],
    'smart_car_lease_deals' => [260,56.84],
    'peugeot_contract_hire' => [260,57.98],
    'rent_to_buy_cars_uk' => [260,58.04],
    'piaggio_ape_50' => [260,58.42],
    'transit_van_lease' => [260,58.6],
    'van_leasing_scotland' => [210,50.78],
    'sports_car_lease' => [260,61.39],
    'car_lease_calculator_uk' => [260,61.85],
    'audi_q5_lease_deals' => [260,62.62],
    'tesla_contract_hire' => [210,55.91],
    'personal_car_leasing_scotland' => [210,57.48],
    'car_leasing_nottingham' => [210,59.22],
    'vw_transporter_sportline_lease' => [210,59.56],
    'car_leasing_south_wales' => [210,61.48],
    'company_van_tax_calculator' => [210,62.23],
    'car_leasing_comparison_uk' => [210,62.51],
    'fair_wear_and_tear_guide' => [170,56.74],
    'van_lease_deals_uk' => [170,57.33],
    'audi_rs6_hire' => [140,49.33],
    'commercial_van_leasing' => [170,58.79],
    'bik_car_tax_calculator' => [170,59.93],
    'audi_hire' => [170,60.42],
    'auto_leasing' => [170,61.27],
    'lease_calculator_uk' => [140,53.34],
    'tesla_model_s_lease_uk' => [170,61.84],
    'l200_lease_deals' => [170,61.92],
    'capital_car_leasing' => [170,62.11],
    'audi_rs3_hire' => [140,54.56],
    'van_leasing_special_offers' => [140,54.59],
    '12_month_personal_car_lease' => [170,62.8],
    'citroen_van_lease' => [170,62.92],
    'no_initial_payment_car_leasing' => [140,55.79],
    'car_lease_tax' => [110,44.44],
    'excess_mileage_charge_calculator' => [140,56.55],
    'lambo_hire' => [110,45.26],
    'car_leasing_websites' => [140,57.13],
    'business_car_leasing_tax_implications' => [110,45.44],
    'courtesy_car_leasing' => [110,45.59],
    'car_benefit_in_kind_tax_calculator' => [140,58.93],
    'leasys_car_leasing' => [90,37.21],
    'tesla_car_lease' => [140,59.65],
    'electric_van_lease' => [140,59.81],
    'sq5_lease' => [140,60.05],
    'businesscar' => [140,60.41],
    'glc_coupe_lease_deals' => [140,60.72],
    'porsche_contract_hire' => [140,60.91],
    'new_business_car_lease' => [140,61.15],
    'audi_a4_estate_lease' => [140,61.29],
    'tesla_lease_deals' => [140,61.67],
    'peugeot_traveller_lease' => [140,62.01],
    'premium_car_lease' => [140,62.06],
    'infiniti_q30_lease_deals' => [140,62.3],
    'lease_purchase_vans' => [140,62.4],
    'amt_it' => [90,41.85],
    'mercedes_x_class_lease' => [140,62.66],
    'citroen_c4_grand_picasso_lease' => [140,62.86],
    'van_leasing_with_insurance_included' => [140,63],
    'van_contract_hire_and_leasing_special_offers' => [110,53.28],
    'limited_company_car_lease' => [110,54.76],
    'leasing_auta_w_uk' => [90,45.15],
    '4x4_pickup_leasing' => [110,55.29],
    'poor_credit_van_leasing' => [110,55.68],
    'phantom_car_hire' => [110,55.97],
    'cayman_lease_special' => [90,47.77],
    'van_lease_offers' => [110,57.39],
    'iveco_daily_70c21' => [90,48.28],
    'car_leasing_stockport' => [110,57.88],
    'personal_car_leasing_bad_credit' => [110,57.89],
    'vw_transporter_lease_deals' => [110,58.99],
    'hitachi_capital_car_leasing' => [110,59.02],
    'smart_track_vehicle_tracking' => [70,35.97],
    'range_rover_evoque_convertible_lease' => [110,60.03],
    'contract_hire_and_leasing_vans' => [110,60.4],
    'business_car_leasing_bmw' => [110,60.4],
    'difference_between_hire_and_lease' => [90,51.91],
    'car_leasing_poor_credit_history' => [110,60.97],
    'porsche_panamera_lease_deals' => [110,61.2],
    'porsche_991_lease' => [90,52.84],
    'contract_hire_and' => [110,61.73],
    'bentley_mulsanne_hire' => [90,53.42],
    'cheapest_tesla_lease' => [110,61.9],
    'maserati_lease_uk' => [110,62.01],
    'global_van_hire' => [110,62.11],
    'discovery_4_lease' => [110,62.37],
    'bentley_gtc_hire' => [90,54.15],
    'smart_leasing' => [110,62.5],
    'cheap_lease_vans' => [110,62.57],
    'porsche_cayman_hire' => [90,54.34],
    'porsche_car_lease' => [110,62.76],
    'ingenium_dynamics_dashboard' => [90,54.57],
    'c63_lease_deals' => [110,62.88],
    'peugeot_van_lease' => [110,62.92],
    'lamborghini_finance_calculator' => [90,55.25],
    'pick_up_truck_contract_hire_deals' => [90,56.55],
    'car_trackers_leeds' => [90,56.82],
    'aston_martin_rapide_s_hire' => [70,45.18],
    'personal_car_leasing_poor_credit' => [90,57.89],
    'audi_tt_convertible_lease_deals' => [90,58.17],
    'bentley_bentayga_hire_uk' => [70,46.25],
    'tax_implications_of_leasing_a_car' => [70,46.76],
    'business_car_lease_criteria' => [90,58.66],
    'new_van_lease' => [90,59.26],
    'cla_shooting_brake_lease' => [90,59.36],
    'amt_solutions' => [70,48.01],
    'difference_between_finance_lease_and_contract_hire' => [90,59.75],
    'ford_ranger_personal_lease_deals' => [90,60.07],
    'iveco_daily_35c16' => [70,48.89],
    'mitsubishi_l200_lease_deals' => [90,60.41],
    'leasing_audi_q7_e_tron' => [90,60.41],
    'compare_van_lease' => [90,60.44],
    'fair_condition_car' => [90,60.82],
    'personal_contract_hire_do_i_need_gap_insurance' => [90,61.65],
    'amt_s' => [90,61.76],
    'citroen_contract_hire' => [90,61.98],
    'info_lease' => [90,62.11],
    'lease_purchase_companies' => [90,62.24],
    'lexus_lease_options' => [90,62.4],
    'black_horse_leasing' => [90,62.4],
    'lease_to_own_business' => [90,62.52],
    'first_class_auto_leasing' => [90,62.63],
    '640_4' => [90,62.63],
    'arval_contact_email' => [90,62.72],
    'bmw_2_year_lease' => [90,62.87],
    'business_contract_hire_tax_implications' => [70,53.22],
    'crew_cab_lease_hire' => [70,54.87],
    'vrs_car_leasing' => [70,54.91],
    'van_lease_specials' => [70,56.11],
    'business_vans_lease' => [70,57.43],
    'subaru_impreza_contract_hire' => [70,57.7],
    'lease_residual_value_guide' => [70,58.02],
    'tesla_model_s_leasing' => [70,58.76],
    'crew_cab_vans_lease_hire' => [70,59.05],
    'how_to_lease_a_vehicle_for_a_business' => [70,59.23],
    'your_new_car_leasing' => [70,59.47],
    'isuzu_blade_contract_hire' => [70,59.75],
    'new_vans_for_lease' => [70,59.96],
    'cheap_car_leasing_bad_credit' => [70,60.02],
    'maserati_car_hire' => [70,60.04],
    'black_horse_contract_hire' => [70,60.15],
    'car_leasing_scotland_bad_credit' => [70,61.21],
    'abarth_695_lease' => [70,61.28],
    'ford_ranger_wildtrak_leasing' => [70,61.36],
    'best_luxury_car_lease_deals_uk' => [70,61.67],
    'ldv_v80_price_uk' => [70,61.82],
    'lease_price_calculator' => [70,61.88],
    'infiniti_lease_uk' => [70,62.03],
    'ford_transit_van_lease' => [70,62.3],
    'ford_ranger_lease_deals_uk' => [70,62.32],
    'contract_hire_and_leasing_difference' => [70,62.33],
    'leasing_audi_a3_sportback' => [70,62.37],
    'lease_m140i' => [70,62.38],
    'g63_lease' => [70,62.42],
    'jaguar_xe_r_sport_lease_deals' => [70,62.45],
    'discovery_sport_contract_hire_deals' => [70,62.8],
    'lamborghini_gallardo_lease_price' => [50,53.74],
    'lease_hire_co_uk' => [40,42.69],
    'vehicle_leasing_scotland' => [50,55.58],
    '2_year_van_lease_deals' => [50,55.88],
    'van_contract_hire_deals' => [50,56.69],
    'mercedes_benz_e_class_lease_deals' => [50,58.34],
    'business_van_lease_deals' => [50,59.37],
    'car_lease_12_month_contract' => [50,59.52],
    'mini_lease_calculator' => [40,50.06],
    'minilease' => [40,50.21],
    'audi_a3_cabriolet_lease' => [50,61.38],
    'contract_vans' => [40,58.2],
    'company_car_and_fuel_tax_calculator' => [40,59.07],
    'car_tax_calculator_company' => [40,59.72],
    'company_car_lease_tax' => [30,47.27],
    'ford_transit_lease_deals' => [40,60.82],
    'buy_amt_uk' => [40,61.02],
    'nissan_leasing_company' => [40,62.18],
    'porsche_boxster_hire' => [40,62.18],
    'audi_a3_sportback_personal_lease' => [40,62.59],
    'simple_car_leasing' => [30,53.62],
    'lease_my_car' => [30,56.17],
    'new_business_van_leasing' => [30,56.2],
    'prestige_vehicle_leasing' => [30,56.36],
    'tm_van_hire' => [30,58.21],
    'ferrari_f40_hire' => [30,59.01],
    'compare_van_lease_deals' => [30,59.12],
    'vauxhall_corsa_contract_hire' => [30,60.97],
    'company_car_or_cash_allowance' => [30,61.59],
    'vw_amarok_contract_hire' => [30,62],
    'vehicle_hire_and_leasing' => [30,62.1],
    'global_rental_&_leasing' => [20,46.02],
    'porsche_lease_calculator' => [20,48.68],
    'ferrari_california_hire' => [20,49.8],
    '12_month_van_lease' => [20,51.53],
    'vehicle_leasing_solutions' => [20,52.2],
    'aston_martin_lease_deals' => [20,54.2],
    'bentley_continental_gt_hire' => [20,54.49],
    'transit_deals' => [20,55.28],
    'car_benefit_tax_calculator' => [20,56.37],
    'guaranteed_lease_hire' => [20,56.38],
    'audi_a1_sportback_lease_deals' => [20,59.36],
    'new_van_lease_deals' => [20,59.71],
    'sprinter_lease_deals' => [20,59.88],
    'bmw_contract_hire_and_leasing_special_offers' => [20,59.92],
    'cheap_bentley_hire' => [20,60.81],
    'porsche_carrera_s_lease' => [20,61.34],
    'audi_a8_lease_deals' => [20,61.4],
    'ferrari_lease_payment' => [20,61.53],
    'business_van_finance' => [20,62.21],
    'ford_ranger_lease_hire' => [20,62.44],
    'leasing_vw_amarok' => [20,62.61],
    'audi_a4_car_lease' => [20,62.69],
    'audi_rs5_hire' => [10,40.49],
    'perk_calculator' => [10,40.56],
    'shogun_catering' => [10,41.02],
    'lease_a_kia_soul_for_99' => [10,42.41],
    'ferrari_ff_hire' => [10,44.1],
    'vehicle_lease_management' => [10,45.19],
    'ferrari_hire_leeds' => [10,46.24],
    'aventador_hire' => [10,47.11],
    'easy_car_leasing' => [10,48.06],
    'aston_martin_vanquish_hire' => [10,48.42],
    'isuzu_contract_hire' => [10,48.77],
    'lease_mileage' => [10,49.45],
    'amt_uk' => [10,49.73],
    'bmw_m5_hire' => [10,49.94],
    'aston_martin_rapide_hire' => [10,50.73],
    'guaranteed_van_finance_no_deposit' => [10,51.33],
    'contract_hire_vans_uk' => [10,52.26],
    'amt_ltd' => [10,53.54],
    'vans_for_lease_uk' => [10,53.77],
    'no_credit_check_van_contract_hire' => [10,53.96],
    'vans_lease_deals' => [10,54.3],
    'how_do_i_lease_a_car_through_my_business' => [10,54.3],
    'lease_exchange' => [10,54.5],
    'lexus_hybrid_lease_deals' => [10,54.91],
    'van_lease_purchase_no_deposit' => [10,54.95],
    'poor_credit_leasing' => [10,55.27],
    'lotus_lease' => [10,55.38],
    'car_leasing_blackburn' => [10,55.38],
    'retail_complaints_procedure' => [10,55.52],
    'swift_car_lease' => [10,55.73],
    'vw_sportline_lease' => [10,56.29],
    'vivaro_lease_deals' => [10,56.38],
    'lease_hire_vans_uk' => [10,56.48],
    'car_lease_deals_scotland' => [10,56.67],
    'lease_any_car' => [10,56.76],
    'vw_transporter_contract_hire' => [10,56.9],
    'amt_group' => [10,57.29],
    'adt_special_deals' => [10,57.31],
    'bad_credit_contract_hire' => [10,57.42],
    'bad_credit_contract_hire' => [10,57.42],
    'van_leasing_made_simple' => [10,57.48],
    'finance_lease_or_contract_hire' => [10,57.82],
    'van_lease_hire_deals' => [10,57.95],
    'nissan_van_lease' => [10,58.29],
    'commercial_van_finance' => [10,58.31],
    'add_tax_calculator' => [10,58.42],
    'vehicle_contracts_and_leasing' => [10,58.67],
    'alpha_car_leasing' => [10,58.68],
    'porsche_911_carrera_s_lease' => [10,58.68],
    'how_to_lease_a_van' => [10,58.89],
    'hybrid_suv_lease_specials' => [10,58.97],
    '320i_lease' => [10,59.03],
    'lotus_elise_lease' => [10,59.21],
    'best_van_contract_hire_deals' => [10,59.4],
    'vehicle_contracts_ltd' => [10,59.64],
    'contract_lease_vans' => [10,59.71],
    'mitsubishi_l200_lease_hire' => [10,59.71],
    'car_leasing_faq' => [10,59.73],
    'mitsubishi_outlander_contract_hire' => [10,59.73],
    'bentley_gt_hire' => [10,59.76],
    'renault_twizy_hire' => [10,60],
    'personal_contract_hire_bad_credit' => [10,60.03],
    'e63_amg_lease' => [10,60.25],
    'contract_hire_vs_lease' => [10,60.29],
    'leasing_process' => [10,60.35],
    'personal_car_tax_calculator' => [10,60.36],
    'subaru_contract_hire' => [10,60.54],
    'cheap_van_leasing_for_bad_credit' => [10,60.61],
    'cayman_s_lease' => [10,60.64],
    'how_much_is_it_to_lease_a_lamborghini' => [10,60.75],
    'cayenne_lease' => [10,60.83],
    'compare_leasing_quotes' => [10,60.86],
    'fiat_ducato_cab_chassis' => [10,61.25],
    'transit_lease_deals' => [10,61.26],
    'mitsubishi_warrior_lease' => [10,61.28],
    'piaggio_ape_van' => [10,61.32],
    'van_lease_prices' => [10,61.4],
    'ford_transit_van_lease_deals' => [10,61.54],
    'fiat_doblo_cargo_dimensions' => [10,61.58],
    'vw_amarok_leasing' => [10,61.71],
    'compare_contract_hire_and_leasing' => [10,61.72],
    'salary_package_car_calculator' => [10,61.86],
    'hyundai_van_lease' => [10,61.92],
    'maserati_lease_deals' => [10,61.94],
    '12_month_auto_lease' => [10,61.94],
    'porsche_boxster_lease_deals' => [10,62.01],
    'a7_lease' => [10,62.08],
    'volvo_car_lease' => [10,62.1],
    'alfa_romeo_leasing' => [10,62.11],
    'windmill_car_leasing' => [10,62.14],
    'bmw_3_series_touring_lease_deals' => [10,62.17],
    'macan_lease_deals' => [10,62.41],
    'lease_hire_range_rover_sport' => [10,62.46],
    'private_car_leasing_scotland' => [10,62.47],
    'lex_personal_car_leasing' => [10,62.48],
    'best_van_lease_deals_uk' => [10,62.52],
    'leasing_for_business' => [10,62.6],
    'arval_contract_hire' => [10,62.61],
    '3_series_lease' => [10,62.71],
    'personal_car_leasing_deals_with_maintenance' => [10,62.74],
    'co_car_tax_calculator' => [10,62.83],
    'citroen_c4_grand_picasso_lease_deals' => [10,62.83],
    'citroen_berlingo_van_lease_deals' => [10,62.84],
    'toyota_hilux_leasing' => [10,62.84],
    'ranger_lease' => [10,62.86],
    'range_rover_hire_leeds' => [10,62.88],
    'van_contract_purchase' => [10,62.96],
    'hybrid_car_lease_specials' => [10,63],    
);